### PR TITLE
Fix non-facade classes will result in no autocomplete

### LINKED ISSUE #784: Laravel added aliases for 'Arr' and 'Str' no autocomplete from helper
ide-helper version: 2.6.2

In Laravel 5.8.3 aliases were added for the `Arr` and `Str` classes by default: 

https://github.com/laravel/laravel/pull/4951

They are **not added as a `Facade`** though just `alias` of a `class`, **I assume this is the issue**:
```php
'Arr' => Illuminate\Support\Arr::class,
'Str' => Illuminate\Support\Str::class,
```

In `PHPStorm` I am not getting any autcomplete functions for these classes:
image

Do I need to create my own `Facade` for these classes?

---
**ide-helper.php**
The `ide-helper` outputs this in the `ide-helper.php` file:

```php
...
namespace Illuminate\Support { 

    class Arr {
         
    }

    class Str {
         
    }
 
}
...
namespace  { 
    ....

    class Arr extends \Illuminate\Support\Arr {}

    ....

    class Str extends \Illuminate\Support\Str {}

    ....
}
...
```

---

**Temporary solution**
I get autocomplete if I remove this section from the `ide-helper.php` but this file is regenerated often. 

```php
...
namespace Illuminate\Support { 

    class Arr {
         
    }

    class Str {
         
    }
 
}
```

### PR DESCRIPTION
**Pull request by netpok**
Currently non-facade classes are resulting non functioning autocomplete. The reason of this that an empty class will be defined in the ide helper class, which will be used for the auto-completion. This pull request prevents this behavior by only handling facades in the namespaced part of the helper file.

Unlike #802  this pull request will keep the alias registration.

Fixes #784

### CODE REVIEW

**Comment by mfn** [comment]
https://github.com/barryvdh/laravel-ide-helper/pull/841/files?w=1 :-)

**Comment by netpok** [comment]
Hoops, I accidentally removed the spaces (not that they should be there).

**Comment by mfn** [comment]
Seems to me this is the same as https://github.com/barryvdh/laravel-ide-helper/pull/802 but with less "noise"?

**Comment by netpok** [comment]
Sorry for the late reply, the problem with #802 is that it will remove the Arr and Str classes from the
```php
namespace{
    // ...
}
```
section so the \Arr and \Str calls will lose autocomplete.

Also the import
```php
use Illuminate\Support\Facades;
```
should be
```php
use Illuminate\Support\Facades\Facade;
```
because currently it filters out all the facades. I think this was some newer change because originally it worked for me (I think).

---

This version does not have the mentioned issues. Also I rebased my pull request to the latest master.

**Review by nalatreb — COMMENTED** [review]
I think you should update your branch, because there are changes in this method: `getAliasesByExtendsNamespace`

**Comment by netpok** [comment]
Ok. I rebased it to current master.

File: resources/views/helper.php [hunk 1]
```diff
@@ -21,15 +21,12 @@
  */
 
 <?php foreach ($namespaces_by_extends_ns as $namespace => $aliases) : ?>
-    <?php if ($namespace == '\Illuminate\Database\Eloquent') :
-        continue;
-    endif; ?>
```
Comment (mfn) [inline resources/views/helper.php:26]: Why is this removed?

Comment (netpok) [reply resources/views/helper.php:26]: It was originally filtered out because it's not a facade so it doesn't need to be there but all non facade classes are filtered out already.

Comment (mfn) [reply resources/views/helper.php:26]: Ah, nice, thank you 👍

**Review by mfn — APPROVED** [review]
Generally LGTM

There's one thing I'm not sure: AFAIK people sometimes expect non-Facades also to show up here, which would have happened before.

Also I hope at some day we can have some tests for this, but I see that this isn't easy here…

**Comment by netpok** [comment]
Basically you don't want the non Facade classes show up there as they would be empty and break the aliased classes. They still show up in the alias section, so `Illuminate\Support\Arr` will not be here but `\Arr extends Illuminate\Support\Arr` will be here.

**Comment by mfn** [comment]
Thank you for your clarification, makes sense to me!

**Comment by netpok** [comment]
Does this PR needs any more attention from me or is it good for now?

**Comment by mfn** [comment]
Good question, I think we wait for approval from @barryvdh 

image

**Comment by netpok** [comment]
@barryvdh Any blocking reason here I should resolve?

**Comment by KentarouTakeda** [comment]
@barryvdh @mfn 
Do we have any update?
With this nice fix, It will prevent phpstan>=1.7 from reporting many errors to empty helper class.

**Comment by mfn** [comment]
Still has my 👍🏼 !

**Comment by snmatsui** [comment]
ping
